### ISSUE TITLE
Доделать окно авторизации

### ISSUE THREAD

**Issue by khbminus** [khbminus/fastTyping#18]
Сейчас есть бекэнд для авторизации (см. #8), но нет фронтенда.

**Comment by Hello-zoka** [comment]
Оно есть, в ветке login-client, там осталось только связать это послав json

**Comment by khbminus** [comment]
Изменил название, чтобы душно не было

**Comment by jegorpopow** [comment]
Кажется, для их работы на клиенете нужно описание API авторизации

**Comment by Hello-zoka** [comment]
Я писал это комментом в коде. Как на кленте, так и на сервере(возможно это в разных ветках)
В регистрации мы хотим послать на сервер логин и пароль и получить ок/не ок в зависимости от существования такого имени

в логине мы на сервер посылаем имя и пароль и в ответ получаем ок/не ок + id пользователя

в смене пароля - тоже самое что логин, только отправляем второй пароль

**Comment by jegorpopow** [comment]
Если можно, добавь описание #23
