### ISSUE TITLE
Стратегии обработки перехода между словами

### ISSUE THREAD

**Issue by jegorpopow** [khbminus/fastTyping#20]
На данный момент локальный менеджер игры для перехода к следующему слову (очистки строки ввода и т.д.) требует после завершения слова нажать пробел для перехода к следующему, а сервер - нет. В результате консенсус между клиентом и сервером не достигается.

**Comment by Hello-zoka** [comment]
кажется тут именно на сервере проблема, мы вроде именно через пробел договаривались
