### ISSUE TITLE
Фикс небольших багов клавивиатуры

### ISSUE THREAD

**Issue by jegorpopow** [khbminus/fastTyping#44]
Елси при многократном нажатии шрифта открывается диалоговое окно залипания клавиш, клавиатура не фиксирует отжатие шифта, и оставляет буквы в верхнеи регистре + при переключении раскладок он странно реагирует.

**Comment by khbminus** [comment]
Проблема на самом деле связана с тем, что там теряется фокус на окно и отжимается шифт(  Я попробовал исправить и может быть станет лучше, но скорее нет, чем да
