### ISSUE TITLE
Связывание клиент и сервера

### ISSUE THREAD

**Issue by khbminus** [khbminus/fastTyping#9]
Нужно связать клиент и сервер: сейчас на клиенте вместо обращений на сервере стоят заглушки.

Основная проблема:  сейчас нужно уметь поддерживать синхронные и асинхронные запросы.

**Comment by khbminus** [comment]
Трекается с помощью #7

**Comment by jegorpopow** [comment]
Нашел решение, планирую имплементировать в ближайшее время

**Comment by jegorpopow** [comment]
Я добавил первые наброски, для того, чтобы нормально упарвлять клиентом, кажется, понадобится немного его поменять, поэтому я поговорб с Юрой
f75351be249ba0f45d971d503b154b973890e9f9

**Comment by jegorpopow** [comment]
UPD 7cacb29207f908e000ec5dc3c67c4847821eca22

**Comment by jegorpopow** [comment]
Проблемы трекаются в https://github.com/khbminus/fastTyping/issues/20, поэтому я закрываю это
